# Generated by Django 4.1.3 on 2023-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citing_article_doi', models.CharField(db_index=True, max_length=255)),
                ('cited_article_doi', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Citations',
                'db_table': 'citation',
                'unique_together': {('citing_article_doi', 'cited_article_doi')},
            },
        ),
    ]
