# Generated by Django 4.1.3 on 2023-02-04 20:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("paper_count", models.IntegerField(blank=True, null=True)),
                ("citation_count", models.IntegerField(blank=True, null=True)),
                ("h_index", models.IntegerField(blank=True, null=True)),
                (
                    "affiliations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Authors",
            },
        ),
    ]
