# Generated by Django 4.1.3 on 2022-12-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogbase',
            old_name='s2ag_papers',
            new_name='s2ag_paper_identifiers',
        ),
        migrations.RenameField(
            model_name='catalogextension',
            old_name='s2ag_papers',
            new_name='s2ag_paper_identifiers',
        ),
    ]
