# Generated by Django 4.1.3 on 2022-12-11 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_rename_s2ag_papers_catalogbase_s2ag_paper_identifiers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogbase',
            unique_together={('owner', 'catalog_name')},
        ),
    ]
