# Generated by Django 4.1.3 on 2022-12-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogbase_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogextension',
            name='owner',
        ),
    ]
