# Generated by Django 4.1.3 on 2023-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_articleidentifier_alter_article_options"),
        ("catalog", "0005_remove_catalogbase_s2ag_paper_identifiers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogbase",
            name="article_identifiers",
            field=models.ManyToManyField(
                related_name="papers_%(class)s", to="article.article"
            ),
        ),
        migrations.AlterField(
            model_name="catalogextension",
            name="article_identifiers",
            field=models.ManyToManyField(
                related_name="papers_%(class)s", to="article.article"
            ),
        ),
    ]
