# Generated by Django 4.1.3 on 2023-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_catalogbase_article_identifiers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogextension",
            name="catalog_extension_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
