# Generated by Django 4.1.3 on 2022-12-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S2AGArticleIdentifier',
            fields=[
                ('s2ag_paperID', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'S2AG Article Identifiers',
            },
        ),
        migrations.CreateModel(
            name='S2AGSearchDisplayArticle',
            fields=[
                ('s2agarticleidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='s2ag.s2agarticleidentifier')),
                ('title', models.TextField()),
                ('abstract', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'S2AG Search Display Articles',
            },
            bases=('s2ag.s2agarticleidentifier',),
        ),
    ]
