# Generated by Django 4.1.3 on 2022-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=255)),
                ('paperId', models.CharField(max_length=255)),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'articles',
            },
        ),
    ]
