# Generated by Django 4.1.3 on 2022-12-04 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_article_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('papers', models.ManyToManyField(related_name='papers_%(class)s', to='search.articleidentifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_extensions', to='search.catalogbase')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('papers', models.ManyToManyField(related_name='papers_%(class)s', to='search.articleidentifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.CreateModel(
            name='S2AGArticleIdentifier',
            fields=[
                ('articleidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.articleidentifier')),
                ('s2ag_paperID', models.CharField(max_length=255)),
            ],
            bases=('search.articleidentifier',),
        ),
        migrations.CreateModel(
            name='S2AGSearchDisplayArticle',
            fields=[
                ('s2agarticleidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.s2agarticleidentifier')),
                ('title', models.TextField()),
                ('abstract', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'articles',
            },
            bases=('search.s2agarticleidentifier',),
        ),
    ]
