from django.urls import path
from .views import *

urlpatterns = [
    path("centrality/betweenness/", BetweennessCentralityView.as_view(), name="betweenness_centrality"),
    path("centrality/closeness/", ClosenessCentralityView.as_view(), name="closeness_centrality"),
    path("centrality/eigenvector/", EigenvectorCentralityView.as_view(), name="eigenvector_centrality"),
    path("centrality/degree/", DegreeCentralityView.as_view(), name="degree_centrality"),
    path("centrality/indegree/", InDegreeCentralityView.as_view(), name="indegree_centrality"),
    path("centrality/outdegree/", OutDegreeCentralityView.as_view(), name="outdegree_centrality"),
    path("centrality/pagerank/", PageRankView.as_view(), name="pagerank"),
    path("centrality/articlerank/", ArticleRankView.as_view(), name="articlerank"),
    path("centrality/harmonic/", HarmonicCentralityView.as_view(), name="harmonic_centrality"),
    path("time_series_centrality/betweenness/", TimeSeriesBetweennessCentralityView.as_view(), name="time_series_betweenness_centrality"),
    path("time_series_centrality/closeness/", TimeSeriesClosenessCentralityView.as_view(), name="time_series_closeness_centrality"),
    path("time_series_centrality/eigenvector/", TimeSeriesEigenvectorCentralityView.as_view(), name="time_series_eigenvector_centrality"),
    path("time_series_centrality/degree/", TimeSeriesDegreeCentralityView.as_view(), name="time_series_degree_centrality"),
    path("time_series_centrality/indegree/", TimeSeriesInDegreeCentralityView.as_view(), name="time_series_indegree_centrality"),
    path("time_series_centrality/outdegree/", TimeSeriesOutDegreeCentralityView.as_view(), name="time_series_outdegree_centrality"),
    path("time_series_centrality/pagerank/", TimeSeriesPageRankView.as_view(), name="time_series_pagerank"),
    path("time_series_centrality/articlerank/", TimeSeriesArticleRankView.as_view(), name="time_series_articlerank"),
    path("time_series_centrality/harmonic/", TimeSeriesHarmonicCentralityView.as_view(), name="time_series_harmonic_centrality"),
    path("diff_time_series_centrality/betweenness/", DiffTimeSeriesBetweennessCentralityView.as_view(), name="diff_time_series_betweenness_centrality"),
    path("diff_time_series_centrality/closeness/", DiffTimeSeriesClosenessCentralityView.as_view(), name="diff_time_series_closeness_centrality"),
    path("diff_time_series_centrality/eigenvector/", DiffTimeSeriesEigenvectorCentralityView.as_view(), name="diff_time_series_eigenvector_centrality"),
    path("diff_time_series_centrality/degree/", DiffTimeSeriesDegreeCentralityView.as_view(), name="diff_time_series_degree_centrality"),
    path("diff_time_series_centrality/indegree/", DiffTimeSeriesInDegreeCentralityView.as_view(), name="diff_time_series_indegree_centrality"),
    path("diff_time_series_centrality/outdegree/", DiffTimeSeriesOutDegreeCentralityView.as_view(), name="diff_time_series_outdegree_centrality"),
    path("diff_time_series_centrality/pagerank/", DiffTimeSeriesPageRankView.as_view(), name="diff_time_series_pagerank"),
    path("diff_time_series_centrality/articlerank/", DiffTimeSeriesArticleRankView.as_view(), name="diff_time_series_articlerank"),
    path("diff_time_series_centrality/harmonic/", DiffTimeSeriesHarmonicCentralityView.as_view(), name="diff_time_series_harmonic_centrality"),
]